### ISSUE TITLE
Breaks compilation in Nativescript 3.3.0

### ISSUE THREAD

**Issue by sm1ddy** [dapriett/nativescript-google-maps-sdk#222]
Hi

Great plugin, I really like it. :)

I've noticed that the Google Maps Sdk plugin seems to break project compilation (at least to Android) after the Nativescript 3.3.0 update.

Here is the log I receive on a fresh project that worked prior to adding the plugin:
`* What went wrong:
Execution failed for task ':transformClassesWithDexForF0F1F2F3F4F5Debug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzbzv;

Unable to apply changes on device: emulator-5554. Error is: Command ./gradlew failed with exit code 1.
`

**Comment by TheOnlyMatt** [comment]
Hello ! 
I had the same error, this happens when there are different google play services version. 
Get the version from the android app.gradle file 
```
project.ext {
        googlePlayServicesVersion = "**11.2.+**"
    }
```

Then set it to the node_modules/nativescript-google-maps-sdk/platforms/android/include.gradle

```
dependencies {
	def googlePlayServicesVersion = project.hasProperty('googlePlayServicesVersion') ? project.googlePlayServicesVersion : '**11.2.+**'
	compile "com.google.android.gms:play-services-maps:$googlePlayServicesVersion"
}
```

In my case I had to replace the "+" version with the "11.2.+"

Hope it can save you from banging your head against the walls as I did :)

**Comment by sm1ddy** [comment]
Thanks mate, that worked. You're a lifesaver.

@dapriett , worth looking into for a more permanent fix probably.

**Comment by dapriett** [comment]
hello all, sorry for the delay - did a search, and looks like it's related to this: https://github.com/NativeScript/android-runtime/issues/878

This broke the ability to set global properties for this and alot of other plugins.  Looks like it should be fixed in 3.3.1.  So you can either try their release candidate (`ns platform add android@rc`), or go back to 3.2.0.  Let me know if the rc version works.

**Comment by sm1ddy** [comment]
Hey @dapriett , thanks for the tip.

Personally, I found android@rc did not resolve the issue... I haven't had a chance to test thoroughly (maybe I did something wrong) but just wanted to let you know.

**Comment by sm1ddy** [comment]
Had a bit more of a look at it, seems I had other problems too.

I fixed them by following this issue:
https://github.com/NativeScript/android-runtime/issues/878

Thanks for your help @dapriett
